# Generated by Django 5.1.6 on 2025-02-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0002_alter_inflow_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at']},
        ),
    ]
